In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load Iris dataset
iris = load_iris()

X = iris.data
y = iris.target

print("Input shape:", X.shape)
print("Classes:", iris.target_names)

Input shape: (150, 4)
Classes: ['setosa' 'versicolor' 'virginica']


Task-1 Loads and prepares Iris dataset

In [4]:
# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale the input features
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

Training data shape: (120, 4)
Testing data shape: (30, 4)


Task - 2 Creates neural network and performs forward propagation

In [5]:
# Set random seed
np.random.seed(42)

# Initialize weights and biases
W1 = np.random.randn(4, 5)
b1 = np.zeros((1, 5))

W2 = np.random.randn(5, 3)
b2 = np.zeros((1, 3))

print("W1 shape:", W1.shape)
print("W2 shape:", W2.shape)

W1 shape: (4, 5)
W2 shape: (5, 3)


Task - 3 Uses ReLU + Softmax and displays predictions

In [6]:
def relu(x):
    return np.maximum(0, x)

In [7]:
def softmax(x):
    exp_values = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_values / np.sum(exp_values, axis=1, keepdims=True)

In [8]:
# Forward propagation

# Input → Hidden layer
Z1 = np.dot(X_test, W1) + b1
A1 = relu(Z1)

# Hidden → Output layer
Z2 = np.dot(A1, W2) + b2
A2 = softmax(Z2)

# Predicted class
predictions = np.argmax(A2, axis=1)

print("Predicted classes:")
print(predictions[:10])

print("\nActual classes:")
print(y_test[:10])

Predicted classes:
[0 2 1 1 2 2 0 1 2 2]

Actual classes:
[1 0 2 1 1 0 1 2 1 1]


In [9]:
for i in range(10):
    predicted_name = iris.target_names[predictions[i]]
    actual_name = iris.target_names[y_test[i]]

    print(
        f"Sample {i+1}: "
        f"Predicted = {predicted_name}, "
        f"Actual = {actual_name}"
    )

Sample 1: Predicted = setosa, Actual = versicolor
Sample 2: Predicted = virginica, Actual = setosa
Sample 3: Predicted = versicolor, Actual = virginica
Sample 4: Predicted = versicolor, Actual = versicolor
Sample 5: Predicted = virginica, Actual = versicolor
Sample 6: Predicted = virginica, Actual = setosa
Sample 7: Predicted = setosa, Actual = versicolor
Sample 8: Predicted = versicolor, Actual = virginica
Sample 9: Predicted = virginica, Actual = versicolor
Sample 10: Predicted = virginica, Actual = versicolor


In [10]:
print("Output probabilities:")
print(A2[:5])

Output probabilities:
[[3.47929208e-01 3.24023165e-01 3.28047626e-01]
 [3.94219098e-07 4.65811966e-08 9.99999559e-01]
 [6.62731129e-02 7.73057403e-01 1.60669484e-01]
 [3.07386790e-01 3.65444960e-01 3.27168249e-01]
 [1.64484836e-01 1.96208415e-01 6.39306749e-01]]
